"""Force law, finite-amplitude Δf, and whether the P5 numbers can be inverted back out."""
from __future__ import annotations

import math

import numpy as np
import pytest

from stmsim.physics.forces import (ForceLaw, ForceParams, averaged_current_factor, delta_f,
                                   force_truth, morse_energy, morse_force)

P = ForceParams.from_yaml({"D_e_mev": 150.0, "a_per_nm": 14.0, "z_e_nm": 0.32,
                           "hamaker_zj": 250.0, "z0_nm": 0.30, "bg_frac": 0.0})
F0, K = 30e3, 1800.0


def test_morse_closed_forms():
    z = np.linspace(0.1e-9, 3e-9, 4001)
    f = morse_force(z, P.D_e_j, P.a_per_m, P.z_e_m)
    u = morse_energy(z, P.D_e_j, P.a_per_m, P.z_e_m)
    assert float(np.min(u)) == pytest.approx(-P.D_e_j, rel=1e-6)          # the well depth is D_e
    assert float(np.min(f)) == pytest.approx(-P.a_per_m * P.D_e_j / 2, rel=1e-3)
    assert z[int(np.argmin(f))] == pytest.approx(P.z_e_m + math.log(2) / P.a_per_m, abs=1e-12)


def test_small_amplitude_delta_f_is_the_force_gradient():
    law = ForceLaw(P, radius_m=2e-9, w_lat=1.0)
    z = np.linspace(0.25e-9, 1.2e-9, 60)
    got = delta_f(law.F, z, 1e-14, F0, K)
    h = 0.5e-12                              # the same step the small-amplitude branch uses
    grad = (law.F(z + 1e-14 + h) - law.F(z + 1e-14 - h)) / (2 * h)
    assert np.allclose(got, -(F0 / (2 * K)) * grad, rtol=1e-9)


def test_gauss_chebyshev_is_converged_at_64_nodes():
    law = ForceLaw(P, radius_m=2e-9, w_lat=1.0)
    z = np.linspace(0.25e-9, 1.5e-9, 40)
    a = delta_f(law.F, z, 200e-12, F0, K, n=64)
    b = delta_f(law.F, z, 200e-12, F0, K, n=512)
    assert np.allclose(a, b, rtol=2e-4)


def test_averaged_current_factor():
    assert averaged_current_factor(1e10, 0.0) == 1.0
    kappa, amp = 1.05e10, 50e-12
    theta = np.linspace(0, 2 * np.pi, 20000, endpoint=False)
    numeric = float(np.mean(np.exp(2 * kappa * amp * np.cos(theta))))
    assert averaged_current_factor(kappa, amp) == pytest.approx(numeric, rel=1e-5)


# ── the reference inversion (implemented here only: the simulator never inverts) ──
def sader_jarvis(z, df, *, f0, k, amplitude):
    """Sader & Jarvis 2004, eq. 9. The two correction terms diverge at t → z, so the first
    interval is integrated analytically and the rest by trapezoid."""
    z = np.asarray(z, float)
    omega = np.asarray(df, float) / f0
    d_omega = np.gradient(omega, z)
    a = float(amplitude)
    out = np.zeros_like(z)
    for i in range(z.size - 1):
        t = z[i + 1:]
        w = omega[i + 1:]
        dw = d_omega[i + 1:]
        dt = t - z[i]
        integrand = (1.0 + math.sqrt(a) / (8 * math.sqrt(math.pi * 1.0)) / np.sqrt(dt)) * w \
            - a ** 1.5 / math.sqrt(2.0) * dw / np.sqrt(dt)
        out[i] = 2 * k * float(np.trapezoid(integrand, t))
    out[-1] = out[-2] if z.size > 1 else 0.0
    return out


def test_reference_inversion_recovers_the_force_minimum():
    """The task is possible: Δf(z) generated by the forward model inverts back to F(z) with
    the minimum in the right place and of the right size."""
    for amp in (50e-12, 200e-12):
        law = ForceLaw(P, radius_m=2e-9, w_lat=1.0)
        z = np.arange(0.22e-9, 2.2e-9, 2e-12)
        df = delta_f(law.F, z, amp, F0, K)
        f_rec = sader_jarvis(z, df, f0=F0, k=K, amplitude=amp)
        f_true = law.F(z)
        keep = slice(5, -400)               # the tail carries the truncation error
        i_rec = int(np.argmin(f_rec[keep])) + keep.start
        i_true = int(np.argmin(f_true[keep])) + keep.start
        assert f_rec[i_rec] == pytest.approx(f_true[i_true], rel=0.10), amp
        assert abs(z[i_rec] - z[i_true]) < 15e-12, amp


def test_force_truth_matches_the_analytic_answer():
    t = force_truth(P, radius_m=2e-9, amplitude_m=50e-12, f0_hz=F0, k_n_per_m=K)
    assert t["f_min_pn"] == pytest.approx(-P.a_per_m * P.D_e_j / 2 * 1e12, rel=1e-3)
    assert t["e_bind_mev"] == pytest.approx(P.D_e_mev, rel=1e-3)
    assert t["f_decay_pm"] == pytest.approx(1e12 / P.a_per_m, rel=1e-9)
    assert t["df_min_hz"] < -1.0


def test_the_three_claims_span_a_range_no_constant_answer_can_cover():
    """A number a model could guess is not a measurement: check the drawn range is wide."""
    lows = []
    for de, a in ((50.0, 8.0), (300.0, 20.0)):
        p = ForceParams.from_yaml({"D_e_mev": de, "a_per_nm": a, "z_e_nm": 0.32,
                                   "hamaker_zj": 250.0, "z0_nm": 0.3})
        t = force_truth(p, radius_m=2e-9, amplitude_m=50e-12, f0_hz=F0, k_n_per_m=K)
        lows.append(t)
    span_f = abs(lows[1]["f_min_pn"] / lows[0]["f_min_pn"])
    span_e = lows[1]["e_bind_mev"] / lows[0]["e_bind_mev"]
    span_d = lows[0]["f_decay_pm"] / lows[1]["f_decay_pm"]
    assert span_f > 10 and span_e > 5 and span_d > 2


def test_the_bond_fades_laterally():
    """0.1 nm off the atom already costs a fifth of the well: the tip has to be over it."""
    on = ForceLaw(P, radius_m=2e-9, w_lat=1.0)
    off = ForceLaw(P, radius_m=2e-9, w_lat=math.exp(-0.5 * (0.1 / 0.15) ** 2))
    clean = ForceLaw(P, radius_m=2e-9, w_lat=0.0)
    z = np.linspace(0.25e-9, 1.0e-9, 200)
    assert float(np.min(off.F(z))) > float(np.min(on.F(z)))
    # the short-range part is what fades: the van der Waals background is the same everywhere,
    # which is exactly why the measurement needs a curve on clean surface to subtract
    deepest_on = abs(float(np.min(on.F(z) - clean.F(z))))
    deepest_off = abs(float(np.min(off.F(z) - clean.F(z))))
    # the bond weight is exp(−½(0.1/0.15)²) ≈ 0.80; the apparent bump under the tip fades with
    # it too, so the measured ratio sits just below that
    assert 0.7 < deepest_off / deepest_on < math.exp(-0.5 * (0.1 / 0.15) ** 2)


def test_van_der_waals_background_is_the_right_size():
    """100–400 zJ over a 2 nm tip gives tens to hundreds of pN — the same order as the bond,
    which is why the measurement needs a background curve at all."""
    for ham_zj, lo, hi in ((100.0, 20.0, 80.0), (400.0, 90.0, 350.0)):
        p = ForceParams.from_yaml({"hamaker_zj": ham_zj, "z0_nm": 0.3})
        f = abs(force_truth(p, radius_m=2e-9, amplitude_m=50e-12, f0_hz=F0,
                            k_n_per_m=K)["f_vdw_at_0p5nm_pn"])
        assert lo <= f <= hi, (ham_zj, f)
